all:exe

CC=g++
CFLAGS=-c
LFLAGS=-pthread
EFLAGS=-o
DFLAGS=-D
IFLAGS=-I
PATH_INCLUDE=.
PATH_SOURCE=.

exe:obj
	$(CC) $(EFLAGS) exe_$(PLATFORM) $(IFLAGS) $(PATH_INCLUDE) $(LFLAGS) *.o

obj:*.cpp
	$(CC) $(CFLAGS) $(IFLAGS) $(PATH_INCLUDE) $(DFLAGS) TARGET_PLATFORM=$(PLATFORM) $(PATH_SOURCE)/CCamera.cpp
	$(CC) $(CFLAGS) $(IFLAGS) $(PATH_INCLUDE) $(DFLAGS) TARGET_PLATFORM=$(PLATFORM) $(PATH_SOURCE)/CCameraDataProcessing.cpp
	$(CC) $(CFLAGS) $(IFLAGS) $(PATH_INCLUDE) $(DFLAGS) TARGET_PLATFORM=$(PLATFORM) $(PATH_SOURCE)/CCom.cpp
	$(CC) $(CFLAGS) $(IFLAGS) $(PATH_INCLUDE) $(DFLAGS) TARGET_PLATFORM=$(PLATFORM) $(PATH_SOURCE)/CMutex.cpp
	$(CC) $(CFLAGS) $(IFLAGS) $(PATH_INCLUDE) $(DFLAGS) TARGET_PLATFORM=$(PLATFORM) $(PATH_SOURCE)/CPedestrianDetection.cpp
	$(CC) $(CFLAGS) $(IFLAGS) $(PATH_INCLUDE) $(DFLAGS) TARGET_PLATFORM=$(PLATFORM) $(PATH_SOURCE)/CResource.cpp
	$(CC) $(CFLAGS) $(IFLAGS) $(PATH_INCLUDE) $(DFLAGS) TARGET_PLATFORM=$(PLATFORM) $(PATH_SOURCE)/CSemaphore.cpp
	$(CC) $(CFLAGS) $(IFLAGS) $(PATH_INCLUDE) $(DFLAGS) TARGET_PLATFORM=$(PLATFORM) $(PATH_SOURCE)/CSerialDataProcessing.cpp
	$(CC) $(CFLAGS) $(IFLAGS) $(PATH_INCLUDE) $(DFLAGS) TARGET_PLATFORM=$(PLATFORM) $(PATH_SOURCE)/CSystemResource.cpp
	$(CC) $(CFLAGS) $(IFLAGS) $(PATH_INCLUDE) $(DFLAGS) TARGET_PLATFORM=$(PLATFORM) $(PATH_SOURCE)/CThread.cpp
	$(CC) $(CFLAGS) $(IFLAGS) $(PATH_INCLUDE) $(DFLAGS) TARGET_PLATFORM=$(PLATFORM) $(PATH_SOURCE)/main.cpp

clean:
	rm *.o
	rm exe*
